config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :likes
  # resources :comments
  # resources :accounts
  # resources :libraries
  # resources :languages
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    get 'registration', to: 'devise/registrations#new'
    post 'registration', to: 'devise/registrations#create'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  #html2haml
  get 'html2haml', action: :index, controller: 'htmltohamls'
  post 'html2haml', action: :html2haml, controller: 'htmltohamls'
  post 'html2haml_bug', action: :bug, controller: 'htmltohamls'

  # static pages
  get 'ideology', action: :ideology, controller: 'static_pages'
  get 'about', action: :about, controller: 'static_pages'
  get 'contact', action: :contact, controller: 'static_pages'
  post 'contact', action: :contact_form, controller: 'static_pages'
  get 'admin', action: :admin, controller: 'static_pages'

  resources :subscribes
  resources :projects
  root 'static_pages#index'
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/free.rb
class Free < User; end

app/models/htmltohaml.rb
class Htmltohaml < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/library.rb
class Library < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  default_scope { where(published: true) }
  scope :not_published, -> { unscoped.where(published: false) }
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  default_scope { where(deleted: false) }
  scope :deleted, -> { unscoped.where(deleted: true) }

  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index; end

  def ideology; end

  def about; end

  def contact
    @contact = Contact.new
  end

  def contact_form; end

  def admin
    render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideology_helper.rb
module IdeologyHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
- content_for :primary_background do
  #particles-js
    %script{ type: 'text/javascript' }
      particlesJS.load('particles-js', '/particlesjs-config-different.json');
    %img.cat{ src: asset_path('cat') }
.about
  .top-block.mt-5

  .center-block.mt-5
    .text-center
      %h3
        What am I doing?
      %br
      %h5
        I creating, I breaking, I exploring, I searching for the best ideas for you, and I create again.
      %br
      %h6
        I am a developer, thinker, engineer, explorer, experimentator, and also a friendly team of one man.

app/views/static_pages/contact.html.haml
.container
  .contact
    .text-center
      .title.mt-5
        %h2
          Contact form
      .form.mt-5
        = form_for(@contact, url: contact_path) do |f|
          = f.text_field :email_from, require: true, id: 'contactEmailFrom',
            class: 'form-control  text-center form-bg-dark black-border-bottom',
            placeholder: 'Email'
          .email-errors
          .invalid-feedback#errorMessageEmail
            ''
          = f.text_area :body, require: true, id: 'contactBody',
            class: 'form-control text-center form-bg-dark black-border-bottom', placeholder: :body, rows: 5
          .body-errors
          .invalid-feedback#errorMessageBody
            ''
          %input{ class: 'form-control  text-center form-bg-dark black-border-bottom',
            id: 'contactCaptcha', placeholder: "Enter the answer: #{rand(10)} + #{rand(10)} = ?" }
          = f.submit 'Send', class: 'btn btn-form-style full-width', disabled: true, id: 'contactSendButton'

app/views/static_pages/ideology.html.haml
- content_for :primary_background do
  #particles-js
    %script{ type: 'text/javascript' }
      particlesJS.load('particles-js', '/particlesjs-config-different.json');
    %img.cat{ src: asset_path('cat') }
.ideology
  .top-block.mt-5

  .center-block.mt-5
    .text-center
      %h3
        Everyone is able to make a small contribution to the development or improvement of the life of mankind.
      %br
      %h2
        So, let's do it!

app/views/static_pages/index.html.haml
- content_for :primary_background do
  #particles-js
    %script{ type: 'text/javascript' }
      particlesJS.load('particles-js', '/particlesjs-config-index.json');
.welcome
  .container
    .top-block.mt-5
      .text-center
        %span.fa.fa-diamond.fa-style
    .center-block.mt-5
      .text-center
        .title
          %h1 Hello world
        .teaser
          %h5
            %b I'm an indie developer, and I want to make our world better than it is.
        .description
          %p Here you can find information about me and my projects.
    .bottom-block
      %br
      .nav
        .row
          .btn-group.btn-vertical
            = link_to 'Ideology', ideology_path, class: 'btn btn-outline-dark'
            = link_to 'About', about_path, class: 'btn btn-outline-dark'
            = link_to 'Projects', projects_path, class: 'btn btn-outline-dark'
            = link_to 'Contact', contact_path, class: 'btn btn-outline-dark'
            = link_to 'Subscribe', new_subscribe_path, class: 'btn btn-outline-dark'