config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :likes
  # resources :comments
  # resources :accounts
  # resources :libraries
  # resources :languages
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    get 'registration', to: 'devise/registrations#new'
    post 'registration', to: 'devise/registrations#create'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  #html2haml
  get 'html2haml', action: :index, controller: 'htmltohamls'
  post 'html2haml', action: :html2haml, controller: 'htmltohamls'
  post 'html2haml_bug', action: :bug, controller: 'htmltohamls'

  # static pages
  get 'ideology', action: :ideology, controller: 'static_pages'
  get 'about', action: :about, controller: 'static_pages'
  get 'contact', action: :contact, controller: 'static_pages'
  post 'contact', action: :contact_form, controller: 'static_pages'
  get 'admin', action: :admin, controller: 'static_pages'

  resources :subscribes
  resources :projects
  root 'static_pages#index'
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/free.rb
class Free < User; end

app/models/htmltohaml.rb
class Htmltohaml < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/library.rb
class Library < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  default_scope { where(published: true) }
  scope :not_published, -> { unscoped.where(published: false) }
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  default_scope { where(deleted: false) }
  scope :deleted, -> { unscoped.where(deleted: true) }

  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  prepend_before_action :redirect_to_development
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {})
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideology_helper.rb
module IdeologyHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/projects/create.html.haml
%h1 Projects#create
%p Find me in app/views/projects/create.html.haml

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/projects/update.html.haml
%h1 Projects#update
%p Find me in app/views/projects/update.html.haml