config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :likes
  # resources :comments
  # resources :accounts
  # resources :libraries
  # resources :languages
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    get 'registration', to: 'devise/registrations#new'
    post 'registration', to: 'devise/registrations#create'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  #html2haml
  get 'html2haml', action: :index, controller: 'htmltohamls'
  post 'html2haml', action: :html2haml, controller: 'htmltohamls'
  post 'html2haml_bug', action: :bug, controller: 'htmltohamls'

  # static pages
  get 'ideology', action: :ideology, controller: 'static_pages'
  get 'about', action: :about, controller: 'static_pages'
  get 'contact', action: :contact, controller: 'static_pages'
  post 'contact', action: :contact_form, controller: 'static_pages'
  get 'admin', action: :admin, controller: 'static_pages'

  resources :subscribes
  resources :projects
  root 'static_pages#index'
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/free.rb
class Free < User; end

app/models/htmltohaml.rb
class Htmltohaml < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/library.rb
class Library < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  default_scope { where(published: true) }
  scope :not_published, -> { unscoped.where(published: false) }
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  default_scope { where(deleted: false) }
  scope :deleted, -> { unscoped.where(deleted: true) }

  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideology_helper.rb
module IdeologyHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_content.html.haml
.content
  .container-fluid
    .row
      .col
        = yield

app/views/layouts/_footer.html.haml
.footer
  %span
    .text-center
      .text-muted
        .mt-2
          = "© Tivgres #{ Date.today.year }"

app/views/layouts/_header.html.haml
.header
  %nav.navbar.navbar-expand-lg.navbar-light.bg-transparent.light-border-bottom.text-dark
    = link_to 'Tivgres', root_path, class: 'navbar-brand'

    %button.navbar-toggler.hide-border{ 'aria-controls': 'navbarColor03', 'aria-expanded': :false,
     'aria-label': 'Toggle navigation', 'data-target': '#navbarColor03',
      'data-toggle': :collapse, type: :button }
      %span.navbar-toggler-icon

    #navbarColor03.collapse.navbar-collapse
      .mr-auto
      .navbar-nav.my-2.my-lg-0
        .nav-item
          - if current_user
            = link_to 'Logout', logout_path, class: 'btn bg-transparent light-hover', method: :delete
          - else
            = link_to 'Login', login_path, class: 'btn bg-transparent light-hover'

app/views/layouts/_modal.html.haml
.modal.fade{ 'aria-labelledby': 'label', role: 'dialog', tabindex: '-1', id: id }
  .modal-dialog.modal-lg{ role: :document }
    .modal-content
      .modal-header
        %h4.modal-title= title
        %button.close{ 'aria-label': :Close, 'data-dismiss': :modal, type: :button }
          %span{'aria-hidden': true} ×
      = yield

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |name, message|
    %div{class: "alert alert-dismissible alert-#{name}"}
      %button.close{ 'data-dismiss': :alert, type: :button } ×
      %h4.alert-heading.text-center
        = "#{name.humanize}!"
      %b
        .text-center
          = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }
    %title Tivgres
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      .primary-background
        = yield :primary_background
      = render 'layouts/header'
      = render 'layouts/notification'
      = render 'layouts/content'
      = render 'layouts/footer'